/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package crawler


class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    val urlSource = SocketConnection().getURLSource("https://therecount.github.io/interview-materials/project-a/1.html")
    val links = UrlExtractor().getLinks(urlSource, "https://therecount.github.io/interview-materials/project-a/")


    println(App().greeting)
}

